/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as Monite from "../../../../index.js";
import * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file")
 *     }
 */
export interface OcrFileUpload {
    document_type?: Monite.OcrDocumentTypeEnum;
    file: core.file.Uploadable.FileLike;
}
