/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index.js";

/**
 * @example
 *     {
 *         client_id: "eb959578-a74d-4ac3-8b25-bf0910027857",
 *         client_secret: "14c84a34-282b-4fd8-8af6-86b5b5f2c212",
 *         grant_type: "client_credentials"
 *     }
 *
 * @example
 *     {
 *         client_id: "eb959578-a74d-4ac3-8b25-bf0910027857",
 *         client_secret: "14c84a34-282b-4fd8-8af6-86b5b5f2c212",
 *         entity_user_id: "7abd8744-507c-40e6-a5ca-34aa480b3991",
 *         grant_type: "entity_user"
 *     }
 */
export interface ObtainTokenPayload {
    /** Your partner [client ID](https://docs.monite.com/get-started/credentials#get-credentials) obtained from the "API Credentials" section of Monite Partner Portal. Note that the sandbox and production environment use different client IDs. */
    client_id: string;
    /** Your partner [client secret](https://docs.monite.com/get-started/credentials#get-credentials) obtained from the "API Credentials" section of Monite Partner Portal. Note that the sandbox and production environment use different client secrets. */
    client_secret: string;
    /** ID of the entity user to generate the access token for. Used only if `grant_type` is `entity_user`. */
    entity_user_id?: string;
    /**
     * The type of the access token to generate:
     *
     *  * `client_credentials` - partner-level access token,
     *  * `entity_user` - entity user token.
     */
    grant_type: Monite.GrantType;
}
