/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         client_id: "client_id",
 *         client_secret: "client_secret",
 *         token: "token"
 *     }
 */
export interface RevokeTokenPayload {
    client_id: string;
    client_secret: string;
    token: string;
}
