/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateRecurrencePayload {
    day_of_month?: Monite.DayOfMonth;
    end_month?: number;
    end_year?: number;
}
