/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index";

/**
 * @example
 *     {}
 */
export interface GetFinancingInvoicesRequest {
    /**
     * Order by
     */
    order?: Monite.OrderEnum;
    /**
     * Max is 100
     */
    limit?: number;
    /**
     * A token, obtained from previous page. Prior over other filters
     */
    pagination_token?: string;
    /**
     * Allowed sort fields
     */
    sort?: Monite.FinancingInvoiceCursorFields;
    /**
     * ID of a payable or receivable invoice.
     */
    invoice_id?: string;
    /**
     * List of invoice IDs.
     */
    invoice_id__in?: string | string[];
    /**
     * Status of the invoice.
     */
    status?: Monite.WcInvoiceStatus;
    /**
     * List of invoice statuses.
     */
    status__in?: Monite.WcInvoiceStatus | Monite.WcInvoiceStatus[];
    /**
     * Type of the invoice. payable or receivable.
     */
    type?: Monite.FinancingInvoiceType;
    /**
     * List of invoice types.
     */
    type__in?: Monite.FinancingInvoiceType | Monite.FinancingInvoiceType[];
    /**
     * Document ID of the invoice.
     */
    document_id?: string;
    /**
     * List of document IDs.
     */
    document_id__in?: string | string[];
    /**
     * Issue date greater than.
     */
    issue_date__gt?: string;
    /**
     * Issue date less than.
     */
    issue_date__lt?: string;
    /**
     * Issue date greater than or equal.
     */
    issue_date__gte?: string;
    /**
     * Issue date less than or equal.
     */
    issue_date__lte?: string;
    /**
     * Due date greater than.
     */
    due_date__gt?: string;
    /**
     * Due date less than.
     */
    due_date__lt?: string;
    /**
     * Due date greater than or equal.
     */
    due_date__gte?: string;
    /**
     * Due date less than or equal.
     */
    due_date__lte?: string;
    /**
     * Created date greater than.
     */
    created_at__gt?: string;
    /**
     * Created date less than.
     */
    created_at__lt?: string;
    /**
     * Created date greater than or equal.
     */
    created_at__gte?: string;
    /**
     * Created date less than or equal.
     */
    created_at__lte?: string;
    /**
     * Total amount of the invoice in minor units.
     */
    total_amount?: number;
    /**
     * Total amount greater than.
     */
    total_amount__gt?: number;
    /**
     * Total amount less than.
     */
    total_amount__lt?: number;
    /**
     * Total amount greater than or equal.
     */
    total_amount__gte?: number;
    /**
     * Total amount less than or equal.
     */
    total_amount__lte?: number;
}
