/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AccountingCustomerRefObject {
    /** A unique identifier of the customer in the accounting system. */
    id: string;
    /** Customer name in the accounting system. */
    company_name?: string;
}
