/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AggregationFunctionEnum = "count" | "average" | "summary" | "min" | "max";
export const AggregationFunctionEnum = {
    Count: "count",
    Average: "average",
    Summary: "summary",
    Min: "min",
    Max: "max",
} as const;
