/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface BankAccountVerifications {
    /** Airwallex Plaid verification */
    airwallex_plaid?: Monite.AirwallexPlaidVerification;
}
