/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface BasedOnReceivableCreatedEventData {
    receivable_id: string;
    type: Monite.ReceivableType;
}
