/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface BizObjectsSchemaInput {
    /** List of objects */
    objects?: Monite.RootSchemaInput[];
}
