/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface BusinessProfileOutput {
    /** Required for US entities. A free-form description of the products the entity sells (whether online or at offline retail stores) or the services it provides to its customers. */
    description_of_goods_or_services?: string;
    /** Required for US entities. The approximate revenue that the business generates per month. */
    estimated_monthly_revenue?: Monite.EstimatedMonthlyRevenue;
    /** The merchant category code of the entity. MCCs are used to classify businesses based on the goods or services they provide. */
    mcc?: string;
    /** Required for US entities. A list of primary countries where the business conducts its operations, such as selling products or providing services. Use two-letter country codes (ISO 3166-2 alpha-2). */
    operating_countries?: Monite.AllowedCountries[];
    /** The business's publicly available website. */
    url?: string;
}
