/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ButtonThemePayload {
    primary_color?: string;
    primary_hover_color?: string;
    secondary_color?: string;
    secondary_hover_color?: string;
}
