/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface CounterpartEinvoicingCredentialResponse {
    id: string;
    network_identifier: string;
    network_schema: Monite.EinvoiceSchemaTypeEnum;
}
