/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface CounterpartRawVatIdUpdateRequest {
    country?: Monite.AllowedCountries;
    type?: string;
    value?: string;
}
