/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

/**
 * This schema is used to update existing counterparts (organizations or individuals).
 */
export type CounterpartUpdatePayload =
    | Monite.CounterpartIndividualRootUpdatePayload
    | Monite.CounterpartOrganizationRootUpdatePayload;
