/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export type CreditNoteResponsePayloadEntity =
    | Monite.CreditNoteResponsePayloadEntity.Organization
    | Monite.CreditNoteResponsePayloadEntity.Individual;

export declare namespace CreditNoteResponsePayloadEntity {
    interface Organization extends Monite.ReceivableEntityOrganization {
        type: "organization";
    }

    interface Individual extends Monite.ReceivableEntityIndividual {
        type: "individual";
    }
}
