/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for credit note line item response. Includes all fields that can be returned from the API.
 */
export interface CreditNoteLineItemResponse {
    /** Unique identifier of the line item */
    id: string;
    /** Timestamp when the line item was created */
    created_at: string;
    /** Timestamp when the line item was last updated */
    updated_at: string;
    /** ID of the user who created the line item */
    created_by_user_id?: string;
    /** ID of the parent credit note */
    credit_note_id: string;
    /** Detailed description of the line item */
    description?: string;
    /** Name or title of the line item */
    name?: string;
    /** Quantity of items */
    quantity?: number;
    /** Subtotal amount before tax */
    subtotal?: number;
    /** Tax percentage */
    tax?: number;
    /** Tax amount */
    tax_amount?: number;
    /** Total amount including tax */
    total?: number;
    /** Unit of measurement */
    unit?: string;
    /** Price per unit in smallest currency unit */
    unit_price?: number;
}
