/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface CurrencySettingsOutput {
    default: Monite.CurrencyEnum;
    exchange_rates?: (Monite.ExchangeRate | undefined)[];
}
