/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DnsRecordPurpose = "DKIM" | "SPF";

export const DnsRecordPurpose = {
    Dkim: "DKIM",
    Spf: "SPF",
} as const;
