/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DocumentTypeEnum =
    | "quote"
    | "invoice"
    | "credit_note"
    | "discount_reminder"
    | "final_reminder"
    | "payables_purchase_order"
    | "overdue_reminder";

export const DocumentTypeEnum = {
    Quote: "quote",
    Invoice: "invoice",
    CreditNote: "credit_note",
    DiscountReminder: "discount_reminder",
    FinalReminder: "final_reminder",
    PayablesPurchaseOrder: "payables_purchase_order",
    OverdueReminder: "overdue_reminder",
} as const;
