/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface EinvoicingConnectionResponse {
    id: string;
    /** Date of Integration */
    created_at: string;
    /** Last update of Integration */
    updated_at: string;
    /** Integration Address */
    address: Monite.EinvoicingAddress;
    /** List of credentials */
    credentials: Monite.EinvoicingNetworkCredentialsResponse[];
    /** ID of the entity */
    entity_id: string;
    /** Set to `true` if the entity needs to receive e-invoices. */
    is_receiver?: boolean;
    /** Set to `true` if the entity needs to send e-invoices. Either `is_sender` or `is_receiver` or both must be `true`. */
    is_sender?: boolean;
    /** Legal name of the Entity */
    legal_name: string;
    /** ID assigned by integration partner */
    provider_id?: string;
    /** Current status of the integration */
    status: string;
}
