/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EntityOnboardingDocuments {
    verification_document_front?: string;
    verification_document_back?: string;
    additional_verification_document_front?: string;
    additional_verification_document_back?: string;
    bank_account_ownership_verification?: string[];
    company_license?: string[];
    company_memorandum_of_association?: string[];
    company_ministerial_decree?: string[];
    company_registration_verification?: string[];
    company_tax_id_verification?: string[];
    proof_of_registration?: string[];
}
