/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface ExchangeRate {
    base: Monite.CurrencyEnum;
    rate: number;
    to: Monite.CurrencyEnum;
}
