/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export type ExportObjectSchema = Monite.ExportObjectSchema.Payable | Monite.ExportObjectSchema.Receivable;

export declare namespace ExportObjectSchema {
    interface Payable extends Monite.ExportPayableSchema {
        name: "payable";
    }

    interface Receivable extends Monite.ExportReceivableSchema {
        name: "receivable";
    }
}
