/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface LineItemFields {
    /** Object describing the required field `measure_unit` of a line item's product */
    measure_unit?: Monite.FieldSchema;
    /** Object describing the required field `tax_rate_value` of a line item */
    tax_rate_value?: Monite.FieldSchema;
    /** Object describing the required field `vat_rate_id` of a line item */
    vat_rate_id?: Monite.FieldSchema;
}
