/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface LineItemUpdate {
    /** Unique identifier of the user-defined vat rate object. */
    custom_vat_rate_id?: string;
    /** The discount for a product. */
    discount?: Monite.Discount;
    /** The actual price of the product in [minor units](https://docs.monite.com/references/currencies#minor-units). */
    price?: number;
    /** The quantity of each of the goods, materials, or services listed in the receivable. */
    quantity?: number;
    /** Specifies the display name of the tax rate. This field is applicable only when tax_rate_value is also provided. */
    tax_rate_name?: string;
    /** Percent minor units. Example: 12.5% is 1250. This field is only required on invoices issued by entities in the US, Pakistan, and other unsupported countries. */
    tax_rate_value?: number;
    /** Unique identifier of the vat rate object. This field is required for all entities in supported countries except the US and Pakistan. */
    vat_rate_id?: string;
}
