/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface LineItem {
    /** ID of the tax rate in the connected accounting system, to be used when pushing the invoice to that accounting system. Use `GET /accounting_tax_rates` to get these IDs. If omitted, Monite will attempt to match the tax rates based on their numeric value. */
    accounting_tax_rate_id?: string;
    /** Unique identifier of the user-defined vat rate object. */
    custom_vat_rate_id?: string;
    /** The discount for a product. */
    discount?: Monite.Discount;
    /** Object of product. Can be used instead of product_id, created in product's catalog */
    product?: Monite.LineItemProductCreate;
    /** Unique identifier of the product. */
    product_id?: string;
    /** The quantity of each of the goods, materials, or services listed in the receivable. */
    quantity: number;
    /** Specifies the display name of the tax rate. This field is applicable only when tax_rate_value is also provided. */
    tax_rate_name?: string;
    /** Percent minor units. Example: 12.5% is 1250. This field is only required on invoices issued by entities in the US, Pakistan, and other unsupported countries. */
    tax_rate_value?: number;
    /** Unique identifier of the vat rate object. This field is required for all entities in supported countries except the US and Pakistan. */
    vat_rate_id?: string;
}
