/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface OcrCreditNote {
    currency?: Monite.CurrencyEnum;
    document_number?: string;
    issue_date?: string;
    line_items: Monite.OcrLineItem[];
    original_invoice_number?: string;
    recipient: Monite.OcrCounterpartDetails;
    sender: Monite.OcrCounterpartDetails;
    subtotal?: number;
    tax_amount?: number;
    tax_rate?: number;
    total_amount?: number;
}
