/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface OcrResponseInvoiceReceiptData {
    /** Counterpart bank ID */
    counterpart_account_id?: string;
    /** The bank account number */
    counterpart_account_number?: string;
    /** Counterpart address */
    counterpart_address?: string;
    /** Counterpart address as a json object compatible with counterparts service */
    counterpart_address_object?: Monite.OcrAddress;
    /** The bank branch number */
    counterpart_branch_number?: string;
    /** Email address of the counterpart */
    counterpart_email?: string;
    /** Counterpart name */
    counterpart_name?: string;
    /** The bank routing number */
    counterpart_routing_number?: string;
    /** Counterpart VAT ID */
    counterpart_vat_id?: string;
    /** ISO 4217 currency code */
    currency?: string;
    /** Discount Raw amount */
    discount_raw?: number;
    /** Document due date in ISO format */
    document_due_date?: string;
    /** Invoice/receipt ID */
    document_id?: string;
    /** Document issuance date in ISO format */
    document_issued_at_date?: string;
    /** List of line items from document raw, without minor units conversion. */
    line_items_raw?: Monite.OcrResponseInvoiceReceiptLineItemRaw[];
    /** Raw payment terms parsed but not calculated. */
    payment_terms_raw?: string[];
    /** Purchase Order Number */
    purchase_order_number?: string;
    /** Tax payer ID */
    tax_payer_id?: string;
    /** Subtotal, without minor units */
    total_excl_vat_raw?: number;
    /** Total paid amount */
    total_paid_amount_raw?: number;
    /** Total, without minor units */
    total_raw?: number;
    /** VAT amount, without minor units */
    total_vat_amount_raw?: number;
    /** VAT Percent raw, without minor units. */
    total_vat_rate_raw?: number;
    type?: "invoice";
}
