/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export type OcrTaskResponseSchemaRecognizedData =
    | Monite.OcrTaskResponseSchemaRecognizedData.Invoice
    | Monite.OcrTaskResponseSchemaRecognizedData.CreditNote
    | Monite.OcrTaskResponseSchemaRecognizedData.Receipt;

export declare namespace OcrTaskResponseSchemaRecognizedData {
    interface Invoice extends Monite.OcrInvoice {
        type: "invoice";
    }

    interface CreditNote extends Monite.OcrCreditNote {
        type: "credit_note";
    }

    interface Receipt extends Monite.OcrReceipt {
        type: "receipt";
    }
}
