/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PayableSettings {
    allow_cancel_duplicates_automatically?: boolean;
    allow_counterpart_autocreation?: boolean;
    allow_counterpart_autolinking?: boolean;
    allow_credit_note_autolinking?: boolean;
    approve_page_url: string;
    /** A state each new payable will have upon creation */
    default_state?: string;
    /** Starting from version 2024-05-25 by default is always set to True. */
    enable_line_items?: boolean;
    skip_approval_for_paid_invoice?: boolean;
}
