/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface PayableTemplatesVariablesObject {
    object_subtype: Monite.PayablesVariableType;
    object_type: Monite.ObjectType;
    variables: Monite.PayableTemplatesVariable[];
}
