/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface PayableCreatedEventData {
    payable_source: Monite.PayableOriginEnum;
}
