/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface PayableValidationsResource {
    required_fields: Monite.PayablesFieldsAllowedForValidate[];
}
