/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PayableCursorFields = "id" | "created_at" | "issued_at";

export const PayableCursorFields = {
    Id: "id",
    CreatedAt: "created_at",
    IssuedAt: "issued_at",
} as const;
