/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface PaymentPageThemeResponse {
    background_color?: string;
    border_radius?: string;
    button?: Monite.ButtonThemeResponse;
    card?: Monite.CardThemeResponse;
    font_color?: string;
    font_family?: string;
    font_link_href?: string;
    logo_src?: string;
}
