/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface PaymentRecordResponse {
    id: string;
    amount: number;
    currency: Monite.CurrencyEnum;
    entity_user_id?: string;
    is_external: boolean;
    object: Monite.PaymentRecordObjectResponse;
    /** Filled in a case, if payment amount is more, than total_amount */
    overpaid_amount?: number;
    paid_at: string;
    payment_intent_id: string;
}
