/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface PaymentAccountObject {
    /** ID of the entity or counterpart that issued the invoice for which you are creating a payment link. */
    id: string;
    type: Monite.PaymentAccountType;
}
