/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Quote statuses.
 */
export type QuoteStateEnum = "draft" | "issued" | "accepted" | "expired" | "declined";
export const QuoteStateEnum = {
    Draft: "draft",
    Issued: "issued",
    Accepted: "accepted",
    Expired: "expired",
    Declined: "declined",
} as const;
