/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface ReceivableFacadeCreateQuotePayload {
    /** List of attachments to include with the receivable. Each attachment can be configured for email inclusion. If not provided, no attachments will be associated. */
    attachments?: Monite.AttachmentRequest[];
    commercial_condition_description?: string;
    /** Address of invoicing, need to state as a separate fields for some countries if it differs from address of a company. */
    counterpart_billing_address_id: string;
    /** Different types of companies for different countries, ex. GmbH, SAS, SNC, etc. */
    counterpart_business_type?: string;
    counterpart_id: string;
    /** Address where goods were shipped / where services were provided. */
    counterpart_shipping_address_id?: string;
    /** Counterpart VAT ID id */
    counterpart_vat_id_id?: string;
    currency: Monite.CurrencyEnum;
    /** The amount of tax deducted in minor units */
    deduction_amount?: number;
    /** A note with additional information about a tax deduction */
    deduction_memo?: string;
    /** The discount for a receivable. */
    discount?: Monite.Discount;
    /** The document number of the receivable, which will appear in the PDF document. Can be set manually only in the [non-compliant mode](https://docs.monite.com/accounts-receivable/regulatory-compliance/invoice-compliance). Otherwise (or if omitted), it will be generated automatically based on the entity's [document number customization](https://docs.monite.com/advanced/document-number-customization) settings when the document is issued. */
    document_id?: string;
    /** Settings for rendering documents in PDF format, including settings for line items and specific document types. */
    document_rendering?: Monite.DocumentRenderingSettings;
    entity?: Monite.ReceivableEntityBase;
    /** Entity bank account ID */
    entity_bank_account_id?: string;
    /** Entity VAT ID id */
    entity_vat_id_id?: string;
    /** The date (in ISO 8601 format) until which the quote is valid. */
    expiry_date?: string;
    /**
     * Optional text displayed below the line items table in the PDF. The text can include [variables](https://docs.monite.com/advanced/variables).
     *
     * See also: `memo`, `commercial_condition_description`.
     */
    footer?: string;
    line_items: Monite.LineItem[];
    /**
     * An optional note for the customer that will be displayed above the line items table in the PDF. The text can include [variables](https://docs.monite.com/advanced/variables).
     *
     * See also: `footer`, `commercial_condition_description`.
     */
    memo?: string;
    /** Metadata for partner needs */
    partner_metadata?: Record<string, unknown>;
    /** ID of the [project](https://docs.monite.com/common/projects) associated with this quote. If specified, the project name will be included in the header of the PDF quote. */
    project_id?: string;
    /** Link for custom quote accept page */
    quote_accept_page_url?: string;
    /** Whether acceptance a quote requires a signature. */
    signature_required?: boolean;
    /** A list of IDs of user-defined tags (labels) assigned to this receivable. */
    tag_ids?: string[];
    /** Trade name of the entity */
    trade_name?: string;
    /** The type of the document uploaded. */
    type: "quote";
    /** Indicates whether the goods, materials, or services listed in the receivable are exempt from VAT or not. */
    vat_exempt?: boolean;
    /** The reason for the VAT exemption, if applicable. */
    vat_exemption_rationale?: string;
    /** Defines whether the prices of products in receivable will already include VAT or not. */
    vat_mode?: Monite.VatModeEnum;
    /** The amount of tax withheld in percent minor units */
    withholding_tax_rate?: number;
}
