/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export type ReceivableUpdatePayload =
    | Monite.UpdateQuotePayload
    | Monite.UpdateInvoicePayload
    | Monite.UpdateCreditNotePayload
    | Monite.UpdateIssuedInvoicePayload;
