/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReceivableEditFlow = "compliant" | "partially_compliant" | "non_compliant";
export const ReceivableEditFlow = {
    Compliant: "compliant",
    PartiallyCompliant: "partially_compliant",
    NonCompliant: "non_compliant",
} as const;
