/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReceivableCounterpartType = "individual" | "organization";

export const ReceivableCounterpartType = {
    Individual: "individual",
    Organization: "organization",
} as const;
