/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

/**
 * Payload of the event.
 */
export type ReceivableHistoryResponseEventData =
    | Monite.StatusChangedEventData
    | Monite.ReceivableUpdatedEventData
    | Monite.ReceivableCreatedEventData
    | Monite.BasedOnReceivableCreatedEventData
    | Monite.PaymentReceivedEventData
    | Monite.MailSentEventData
    | Monite.ReminderMailSentEventData;
