/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface ReceivableMailRecipients {
    bcc?: Monite.ReceivableMailRecipientState[];
    cc?: Monite.ReceivableMailRecipientState[];
    to?: Monite.ReceivableMailRecipientState[];
}
