/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index.js";

export interface ReceivableCounterpartVatIdResponse {
    id: string;
    counterpart_id: string;
    country?: Monite.AllowedCountries;
    type?: Monite.VatIdTypeEnum;
    value: string;
}
