/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ReceiptLineItemResponseSchema {
    /** Unique line item ID. */
    id: string;
    /** Created at. */
    created_at: string;
    /** Updated at. */
    updated_at: string;
    /** Accounting tax rate ID. */
    accounting_tax_rate_id?: string;
    /** Cost center ID. */
    cost_center_id?: string;
    /** Created by user. */
    created_by_entity_user_id?: string;
    /** Line item name. */
    name?: string;
    /** Receipt ID. */
    receipt_id: string;
    /** Total. */
    total?: number;
}
