/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReceivableCursorFields2 =
    | "counterpart_name"
    | "counterpart_id"
    | "amount"
    | "total_amount"
    | "status"
    | "due_date"
    | "issue_date"
    | "document_id"
    | "created_at"
    | "project_id";
export const ReceivableCursorFields2 = {
    CounterpartName: "counterpart_name",
    CounterpartId: "counterpart_id",
    Amount: "amount",
    TotalAmount: "total_amount",
    Status: "status",
    DueDate: "due_date",
    IssueDate: "issue_date",
    DocumentId: "document_id",
    CreatedAt: "created_at",
    ProjectId: "project_id",
} as const;
