/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface RoleResponse {
    /** UUID role ID */
    id: string;
    /** UTC datetime */
    created_at: string;
    /** UTC datetime */
    updated_at: string;
    /** Role name */
    name: string;
    /** Access permissions */
    permissions: Monite.BizObjectsSchema;
    /** record status, 'active' by default */
    status: Monite.StatusEnum;
}
