/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export type RootSchemaOutput =
    | Monite.RootSchemaOutput.ApprovalPolicy
    | Monite.RootSchemaOutput.ApprovalRequest
    | Monite.RootSchemaOutput.Comment
    | Monite.RootSchemaOutput.Counterpart
    | Monite.RootSchemaOutput.CounterpartVatId
    | Monite.RootSchemaOutput.DeliveryNote
    | Monite.RootSchemaOutput.Entity
    | Monite.RootSchemaOutput.EntityBankAccount
    | Monite.RootSchemaOutput.EntityUser
    | Monite.RootSchemaOutput.EntityVatIds
    | Monite.RootSchemaOutput.Export
    | Monite.RootSchemaOutput.Mailbox
    | Monite.RootSchemaOutput.OcrTask
    | Monite.RootSchemaOutput.Onboarding
    | Monite.RootSchemaOutput.OverdueReminder
    | Monite.RootSchemaOutput.Payable
    | Monite.RootSchemaOutput.PayablesPurchaseOrder
    | Monite.RootSchemaOutput.PaymentRecord
    | Monite.RootSchemaOutput.PaymentReminder
    | Monite.RootSchemaOutput.Person
    | Monite.RootSchemaOutput.Product
    | Monite.RootSchemaOutput.Project
    | Monite.RootSchemaOutput.Receivable
    | Monite.RootSchemaOutput.Reconciliation
    | Monite.RootSchemaOutput.Role
    | Monite.RootSchemaOutput.Tag
    | Monite.RootSchemaOutput.TodoTask
    | Monite.RootSchemaOutput.TodoTaskMute
    | Monite.RootSchemaOutput.Transaction
    | Monite.RootSchemaOutput.Workflow;

export namespace RootSchemaOutput {
    export interface ApprovalPolicy extends Monite.CommonSchemaOutput {
        object_type: "approval_policy";
    }

    export interface ApprovalRequest extends Monite.CommonSchemaOutput {
        object_type: "approval_request";
    }

    export interface Comment extends Monite.CommonSchemaOutput {
        object_type: "comment";
    }

    export interface Counterpart extends Monite.CommonSchemaOutput {
        object_type: "counterpart";
    }

    export interface CounterpartVatId extends Monite.CommonSchemaOutput {
        object_type: "counterpart_vat_id";
    }

    export interface DeliveryNote extends Monite.CommonSchemaOutput {
        object_type: "delivery_note";
    }

    export interface Entity extends Monite.CommonSchemaOutput {
        object_type: "entity";
    }

    export interface EntityBankAccount extends Monite.CommonSchemaOutput {
        object_type: "entity_bank_account";
    }

    export interface EntityUser extends Monite.CommonSchemaOutput {
        object_type: "entity_user";
    }

    export interface EntityVatIds extends Monite.CommonSchemaOutput {
        object_type: "entity_vat_ids";
    }

    export interface Export extends Monite.CommonSchemaOutput {
        object_type: "export";
    }

    export interface Mailbox extends Monite.CommonSchemaOutput {
        object_type: "mailbox";
    }

    export interface OcrTask extends Monite.CommonSchemaOutput {
        object_type: "ocr_task";
    }

    export interface Onboarding extends Monite.CommonSchemaOutput {
        object_type: "onboarding";
    }

    export interface OverdueReminder extends Monite.CommonSchemaOutput {
        object_type: "overdue_reminder";
    }

    export interface Payable extends Monite.PayableSchemaOutput {
        object_type: "payable";
    }

    export interface PayablesPurchaseOrder extends Monite.CommonSchemaOutput {
        object_type: "payables_purchase_order";
    }

    export interface PaymentRecord extends Monite.CommonSchemaOutput {
        object_type: "payment_record";
    }

    export interface PaymentReminder extends Monite.CommonSchemaOutput {
        object_type: "payment_reminder";
    }

    export interface Person extends Monite.CommonSchemaOutput {
        object_type: "person";
    }

    export interface Product extends Monite.CommonSchemaOutput {
        object_type: "product";
    }

    export interface Project extends Monite.CommonSchemaOutput {
        object_type: "project";
    }

    export interface Receivable extends Monite.CommonSchemaOutput {
        object_type: "receivable";
    }

    export interface Reconciliation extends Monite.CommonSchemaOutput {
        object_type: "reconciliation";
    }

    export interface Role extends Monite.CommonSchemaOutput {
        object_type: "role";
    }

    export interface Tag extends Monite.CommonSchemaOutput {
        object_type: "tag";
    }

    export interface TodoTask extends Monite.CommonSchemaOutput {
        object_type: "todo_task";
    }

    export interface TodoTaskMute extends Monite.CommonSchemaOutput {
        object_type: "todo_task_mute";
    }

    export interface Transaction extends Monite.CommonSchemaOutput {
        object_type: "transaction";
    }

    export interface Workflow extends Monite.CommonSchemaOutput {
        object_type: "workflow";
    }
}
