/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceProvidersEnum = "codat" | "railz";

export const ServiceProvidersEnum = {
    Codat: "codat",
    Railz: "railz",
} as const;
