/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface SettingsResponse {
    language?: Monite.LanguageCodeEnum;
    currency?: Monite.CurrencySettingsOutput;
    reminder?: Monite.RemindersSettings;
    /** Defines whether the prices of products in receivables will already include VAT or not. */
    vat_mode?: Monite.VatModeEnum;
    /** Payment preferences for entity to automate calculating suggested payment date based on payment terms and entity preferences. */
    payment_priority?: Monite.PaymentPriorityEnum;
    /** Automatically attempt to find a corresponding purchase order for all incoming payables. */
    allow_purchase_order_autolinking?: boolean;
    receivable_edit_flow?: Monite.ReceivableEditFlow;
    document_ids?: Monite.DocumentIDsSettings;
    /** Auto tagging settings for all incoming OCR payable documents. */
    payables_ocr_auto_tagging?: Monite.OcrAutoTaggingSettingsRequest[];
    /** Sets the default behavior of whether a signature is required to accept quotes. */
    quote_signature_required?: boolean;
    /** If enabled, the paid invoice's PDF will be in a new layout set by the user. */
    generate_paid_invoice_pdf?: boolean;
    accounting?: Monite.AccountingSettings;
}
