/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceOfPayableDataEnum = "ocr" | "user_specified";

export const SourceOfPayableDataEnum = {
    Ocr: "ocr",
    UserSpecified: "user_specified",
} as const;
