/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface SystemTemplates {
    /** All pre-defined email templates */
    data: Monite.SystemTemplateDataSchema[];
}
