/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplateTypeEnum = "block" | "source_object";
export const TemplateTypeEnum = {
    Block: "block",
    SourceObject: "source_object",
} as const;
