/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export type UpdateIssuedInvoiceEntity =
    | Monite.UpdateIssuedInvoiceEntity.Organization
    | Monite.UpdateIssuedInvoiceEntity.Individual;

export declare namespace UpdateIssuedInvoiceEntity {
    interface Organization extends Monite.ReceivableEntityOrganizationRequest {
        type: "organization";
    }

    interface Individual extends Monite.ReceivableEntityIndividualRequest {
        type: "individual";
    }
}
