/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WebhookSubscriptionStatus = "enabled" | "disabled";
export const WebhookSubscriptionStatus = {
    Enabled: "enabled",
    Disabled: "disabled",
} as const;
