/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../index";

export interface WebhookSubscriptionResource {
    id: string;
    event_types: string[];
    object_type: Monite.WebhookObjectType;
    status: Monite.WebhookSubscriptionStatus;
    url: string;
}
