/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CommentUpdateRequest {
    reply_to_entity_user_id?: string;
    text?: string;
}
