/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         amount: 1
 *     }
 */
export interface UpdatePaymentIntentPayload {
    amount: number;
}
