/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index";

/**
 * @example
 *     {
 *         date_from: "date_from",
 *         date_to: "date_to",
 *         format: "csv",
 *         objects: [{
 *                 name: "receivable",
 *                 statuses: ["draft"]
 *             }]
 *     }
 */
export interface ExportPayloadSchema {
    date_from: string;
    date_to: string;
    format: Monite.ExportFormat;
    objects: Monite.ExportObjectSchema[];
}
