/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index.js";

/**
 * @example
 *     {
 *         reminder_type: "term_1"
 *     }
 */
export interface ReceivableSendTestReminderPayload {
    recipients?: Monite.Recipients;
    /** The type of the reminder to be sent. */
    reminder_type: Monite.ReminderTypeEnum;
}
