export * as bankAccounts from "./bankAccounts";
export * as onboardingData from "./onboardingData";
export * as paymentMethods from "./paymentMethods";
export * as vatIds from "./vatIds";
export * as persons from "./persons";
export * from "./bankAccounts/client/requests";
export * from "./onboardingData/client/requests";
export * from "./paymentMethods/client/requests";
export * from "./vatIds/client/requests";
export * from "./persons/client/requests";
