export * as bankAccounts from "./bankAccounts/index.js";
export * as onboardingData from "./onboardingData/index.js";
export * as paymentMethods from "./paymentMethods/index.js";
export * as vatIds from "./vatIds/index.js";
export * as persons from "./persons/index.js";
export * from "./bankAccounts/client/requests/index.js";
export * from "./onboardingData/client/requests/index.js";
export * from "./paymentMethods/client/requests/index.js";
export * from "./vatIds/client/requests/index.js";
export * from "./persons/client/requests/index.js";
