/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id__in: "string"
 *     }
 */
export interface FilesGetRequest {
    id__in?: string | string[];
}
