/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         entity_ids: ["entity_ids"]
 *     }
 */
export interface MailboxMultipleEntitiesRequest {
    entity_ids: string[];
}
