/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { MoniteClient } from "../../src/Client";

describe("PartnerSettings", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            api_version: "2024-05-25",
            commercial_conditions: ["commercial_conditions"],
            currency: { default: "AED", exchange_rates: [{ base: "AED", rate: 0.98, to: "AED" }] },
            default_role: { key: "value" },
            mail: { attach_documents_as_pdf: true, from_email_username: "from_email_username", from_name: "from_name" },
            payable: {
                allow_cancel_duplicates_automatically: true,
                allow_counterpart_autocreation: true,
                allow_counterpart_autolinking: true,
                allow_credit_note_autolinking: true,
                approve_page_url: "https://monite.com",
                default_state: "default_state",
                enable_line_items: true,
                skip_approval_for_paid_invoice: true,
            },
            payments: {
                payment_page_domain: "payment_page_domain",
                payment_page_theme: {
                    background_color: "background_color",
                    border_radius: "border_radius",
                    font_color: "font_color",
                    font_family: "font_family",
                    font_link_href: "font_link_href",
                    logo_src: "logo_src",
                },
                support_email: "support_email",
            },
            receivable: { create_without_personal_info: true, deduction_title: "deduction_title" },
            units: [{ designation: "kg", name: "Kilogram" }],
            website: "website",
        };
        server.mockEndpoint().get("/settings").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.partnerSettings.get();
        expect(response).toEqual({
            api_version: "2024-05-25",
            commercial_conditions: ["commercial_conditions"],
            currency: {
                default: "AED",
                exchange_rates: [
                    {
                        base: "AED",
                        rate: 0.98,
                        to: "AED",
                    },
                ],
            },
            default_role: {
                key: "value",
            },
            mail: {
                attach_documents_as_pdf: true,
                from_email_username: "from_email_username",
                from_name: "from_name",
            },
            payable: {
                allow_cancel_duplicates_automatically: true,
                allow_counterpart_autocreation: true,
                allow_counterpart_autolinking: true,
                allow_credit_note_autolinking: true,
                approve_page_url: "https://monite.com",
                default_state: "default_state",
                enable_line_items: true,
                skip_approval_for_paid_invoice: true,
            },
            payments: {
                payment_page_domain: "payment_page_domain",
                payment_page_theme: {
                    background_color: "background_color",
                    border_radius: "border_radius",
                    font_color: "font_color",
                    font_family: "font_family",
                    font_link_href: "font_link_href",
                    logo_src: "logo_src",
                },
                support_email: "support_email",
            },
            receivable: {
                create_without_personal_info: true,
                deduction_title: "deduction_title",
            },
            units: [
                {
                    designation: "kg",
                    name: "Kilogram",
                },
            ],
            website: "website",
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            api_version: "2024-05-25",
            commercial_conditions: ["commercial_conditions"],
            currency: { default: "AED", exchange_rates: [{ base: "AED", rate: 0.98, to: "AED" }] },
            default_role: { key: "value" },
            mail: { attach_documents_as_pdf: true, from_email_username: "from_email_username", from_name: "from_name" },
            payable: {
                allow_cancel_duplicates_automatically: true,
                allow_counterpart_autocreation: true,
                allow_counterpart_autolinking: true,
                allow_credit_note_autolinking: true,
                approve_page_url: "https://monite.com",
                default_state: "default_state",
                enable_line_items: true,
                skip_approval_for_paid_invoice: true,
            },
            payments: {
                payment_page_domain: "payment_page_domain",
                payment_page_theme: {
                    background_color: "background_color",
                    border_radius: "border_radius",
                    font_color: "font_color",
                    font_family: "font_family",
                    font_link_href: "font_link_href",
                    logo_src: "logo_src",
                },
                support_email: "support_email",
            },
            receivable: { create_without_personal_info: true, deduction_title: "deduction_title" },
            units: [{ designation: "kg", name: "Kilogram" }],
            website: "website",
        };
        server
            .mockEndpoint()
            .patch("/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.partnerSettings.update();
        expect(response).toEqual({
            api_version: "2024-05-25",
            commercial_conditions: ["commercial_conditions"],
            currency: {
                default: "AED",
                exchange_rates: [
                    {
                        base: "AED",
                        rate: 0.98,
                        to: "AED",
                    },
                ],
            },
            default_role: {
                key: "value",
            },
            mail: {
                attach_documents_as_pdf: true,
                from_email_username: "from_email_username",
                from_name: "from_name",
            },
            payable: {
                allow_cancel_duplicates_automatically: true,
                allow_counterpart_autocreation: true,
                allow_counterpart_autolinking: true,
                allow_credit_note_autolinking: true,
                approve_page_url: "https://monite.com",
                default_state: "default_state",
                enable_line_items: true,
                skip_approval_for_paid_invoice: true,
            },
            payments: {
                payment_page_domain: "payment_page_domain",
                payment_page_theme: {
                    background_color: "background_color",
                    border_radius: "border_radius",
                    font_color: "font_color",
                    font_family: "font_family",
                    font_link_href: "font_link_href",
                    logo_src: "logo_src",
                },
                support_email: "support_email",
            },
            receivable: {
                create_without_personal_info: true,
                deduction_title: "deduction_title",
            },
            units: [
                {
                    designation: "kg",
                    name: "Kilogram",
                },
            ],
            website: "website",
        });
    });
});
