/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { MoniteClient } from "../../src/Client";

describe("PaymentReminders", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    entity_id: "entity_id",
                    name: "name",
                    status: "active",
                    term_1_reminder: { body: "body", days_before: 1, subject: "subject" },
                    term_2_reminder: { body: "body", days_before: 1, subject: "subject" },
                    term_final_reminder: { body: "body", days_before: 1, subject: "subject" },
                },
            ],
        };
        server.mockEndpoint().get("/payment_reminders").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.paymentReminders.get();
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                    entity_id: "entity_id",
                    name: "name",
                    status: "active",
                    term_1_reminder: {
                        body: "body",
                        days_before: 1,
                        subject: "subject",
                    },
                    term_2_reminder: {
                        body: "body",
                        days_before: 1,
                        subject: "subject",
                    },
                    term_final_reminder: {
                        body: "body",
                        days_before: 1,
                        subject: "subject",
                    },
                },
            ],
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: { bcc: ["bcc"], cc: ["cc"], to: ["to"] },
            status: "active",
            term_1_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_2_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_final_reminder: { body: "body", days_before: 1, subject: "subject" },
        };
        server
            .mockEndpoint()
            .post("/payment_reminders")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.paymentReminders.create({
            name: "name",
        });
        expect(response).toEqual({
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: {
                bcc: ["bcc"],
                cc: ["cc"],
                to: ["to"],
            },
            status: "active",
            term_1_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_2_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_final_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
        });
    });

    test("get_by_id", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: { bcc: ["bcc"], cc: ["cc"], to: ["to"] },
            status: "active",
            term_1_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_2_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_final_reminder: { body: "body", days_before: 1, subject: "subject" },
        };
        server
            .mockEndpoint()
            .get("/payment_reminders/payment_reminder_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.paymentReminders.getById("payment_reminder_id");
        expect(response).toEqual({
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: {
                bcc: ["bcc"],
                cc: ["cc"],
                to: ["to"],
            },
            status: "active",
            term_1_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_2_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_final_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
        });
    });

    test("delete_by_id", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/payment_reminders/payment_reminder_id").respondWith().statusCode(200).build();

        const response = await client.paymentReminders.deleteById("payment_reminder_id");
        expect(response).toEqual(undefined);
    });

    test("update_by_id", async () => {
        const server = mockServerPool.createServer();
        const client = new MoniteClient({
            token: "test",
            moniteVersion: "test",
            moniteEntityId: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: { bcc: ["bcc"], cc: ["cc"], to: ["to"] },
            status: "active",
            term_1_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_2_reminder: { body: "body", days_before: 1, subject: "subject" },
            term_final_reminder: { body: "body", days_before: 1, subject: "subject" },
        };
        server
            .mockEndpoint()
            .patch("/payment_reminders/payment_reminder_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.paymentReminders.updateById("payment_reminder_id");
        expect(response).toEqual({
            id: "id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            entity_id: "entity_id",
            name: "name",
            recipients: {
                bcc: ["bcc"],
                cc: ["cc"],
                to: ["to"],
            },
            status: "active",
            term_1_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_2_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
            term_final_reminder: {
                body: "body",
                days_before: 1,
                subject: "subject",
            },
        });
    });
});
