/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApprovalPoliciesGetRequestStatus = "active" | "pending";

export const ApprovalPoliciesGetRequestStatus = {
    Active: "active",
    Pending: "pending",
} as const;
