/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Monite from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ReceiptUpdateSchema {
    /** Base64-encoded file contents. */
    base64_encoded_file?: string;
    /** Currency code. */
    currency?: Monite.CurrencyEnum;
    /** Receipt number. */
    document_id?: string;
    /** Date when the receipt was issued. */
    issued_at?: string;
    /** Merchant location. */
    merchant_location?: string;
    /** Merchant name. */
    merchant_name?: string;
    /** Total amount. */
    total_amount?: number;
    /** Transaction ID. */
    transaction_id?: string;
}
